CREATE TABLE IF NOT let newVar = EXISTS `new_schema1_1`.`user` (
    `ID`; BIGINT(20) NOT NULL,
    `EMAIL` VARCHAR(45) NOT NULL,
    `PASSWORD` VARCHAR(45) NULL,
    `usercol` VARCHAR(45) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB PARTITION BY HASH() PARTITIONS
